export const LOGIN = {
  REQUEST: "LOGIN_REQUEST",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL",
};

export const LOGOUT = {
  REQUEST: "LOGOUT_REQUEST",
  SUCCESS: "LOGOUT_SUCCESS",
  FAIL: "LOGOUT_FAIL",
};
