export const LOGIN = {
  REQUEST: "ATTORNEY_CREATE_REQUEST",
  SUCCESS: "ATTORNEY_CREATE_SUCCESS",
  FAIL: "ATTORNEY_CREATE_FAIL",
};

export const LOGOUT = {
  REQUEST: "ATTORNEY_CREATE_REQUEST",
  SUCCESS: "ATTORNEY_CREATE_SUCCESS",
  FAIL: "ATTORNEY_CREATE_FAIL",
};
